apiVersion: v1
kind: PersistentVolume
metadata:
  name: paas-pv
  namespace: paas
  labels:
    pv: paas-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.37
    path: "/paas_nfs"
