apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paas-pvc
  namespace: paas
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      pv: paas-pv
