apiVersion: v1
kind: Deployment
metadata:
  name: @project.artifactId@
  namespace: @k8s.namespace@
spec:
  replicas: K8S_REPLICAS
  selector:
    app: @project.artifactId@
  template:
    metadata:
      name: @project.artifactId@
      labels:
        app: @project.artifactId@
    spec:
      containers:
      - name: @project.artifactId@
        image: @docker.image.prefix@/@k8s.namespace@/@project.artifactId@:@project.version@
        imagePullPolicy: Always
        ports:
        - containerPort: @project.port@
        env:
        - name: KUBERNETES_NAMESPACE
          value: @k8s.namespace@
        - name: KUBERNETES_MASTER
          value: @k8s.masterUrl@
        - name: KUBERNETES_TRUST_CERTIFICATES
          value: "true"
        - name: CONFIG_URI
          value: BOOTSTRAP_CONFIG_URI
        - name: CONFIG_LABEL
          value: BOOTSTRAP_CONFIG_LABEL
---
apiVersion: v1
kind: Service
metadata:
  name: @project.artifactId@
  namespace: @k8s.namespace@
  labels: 
    app: @project.artifactId@
spec:
  type: NodePort
  selector:
    app: @project.artifactId@
  ports:
  - port: @project.port@
    targetPort: @project.port@
    nodePort: @k8s.nodeport@